from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import logging
import os
from dotenv import load_dotenv

# Configure Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Load environment variables from project root
basedir = os.path.abspath(os.path.dirname(__file__))
load_dotenv(os.path.join(basedir, "../../.env"))
logger.info(f"OPENAI_API_KEY Found: {'Yes' if os.getenv('OPENAI_API_KEY') else 'No'}")

from agent import generate_jd_ai

app = FastAPI(title="JD Generator API")

# Enable CORS for frontend interaction
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class JDRequest(BaseModel):
    companyName: str
    companyType: str
    industry: str
    location: str
    roleTitle: str
    experience: str
    employmentType: str
    workMode: str
    salary: str

@app.get("/")
async def root():
    return {"status": "JD Generator Backend is Active"}

@app.post("/generate-jd")
async def generate_jd_endpoint(request: JDRequest):
    logger.info(f"Received JD Generation Request for Role: {request.roleTitle} at {request.companyName}")
    try:
        logger.info("Calling AI Agent for intelligent analysis...")
        jd_text = await generate_jd_ai(request.model_dump())
        logger.info("JD successfully generated by AI Agent.")
        return {"status": "success", "jd": jd_text}
    except Exception as e:
        logger.error(f"Error during JD Generation: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
